/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { InputType } from "@nxc/ui/form/core";
import { Size } from "@nxc/ui/core";
export namespace Components {
    interface NxcInput {
        /**
          * The input's autofocus attribute.
         */
        "autofocus": boolean;
        "clearable": boolean;
        /**
          * Set to true to disable the input.
         */
        "disabled": boolean;
        /**
          * Set to true to indicate that the user input is invalid.
         */
        "invalid": boolean;
        "label": string;
        /**
          * The input's max attribute.
         */
        "max": number;
        /**
          * The input's maxlength attribute.
         */
        "maxlength": number;
        /**
          * The input's min attribute.
         */
        "min": number;
        /**
          * The input's minlength attribute.
         */
        "minlength": number;
        "name": string;
        /**
          * The input's pattern attribute.
         */
        "pattern": string;
        /**
          * Set to true to draw a pill-style input with rounded edges.
         */
        "pill": boolean;
        /**
          * The input's placeholder text.
         */
        "placeholder": string;
        /**
          * Set to true for a readonly input.
         */
        "readonly": boolean;
        /**
          * Removes focus from the input.
         */
        "removeFocus": () => Promise<void>;
        /**
          * The input's required attribute.
         */
        "required": boolean;
        /**
          * Selects all the text in the input.
         */
        "select": () => Promise<void>;
        /**
          * Sets focus on the input.
         */
        "setFocus": () => Promise<void>;
        "size": Size;
        /**
          * The input's step attribute.
         */
        "step": number;
        "togglePassword": boolean;
        "type": InputType;
        "valid": boolean;
        "value": string;
    }
}
declare global {
    interface HTMLNxcInputElement extends Components.NxcInput, HTMLStencilElement {
    }
    var HTMLNxcInputElement: {
        prototype: HTMLNxcInputElement;
        new (): HTMLNxcInputElement;
    };
    interface HTMLElementTagNameMap {
        "nxc-input": HTMLNxcInputElement;
    }
}
declare namespace LocalJSX {
    interface NxcInput {
        /**
          * The input's autofocus attribute.
         */
        "autofocus"?: boolean;
        "clearable"?: boolean;
        /**
          * Set to true to disable the input.
         */
        "disabled"?: boolean;
        /**
          * Set to true to indicate that the user input is invalid.
         */
        "invalid"?: boolean;
        "label"?: string;
        /**
          * The input's max attribute.
         */
        "max"?: number;
        /**
          * The input's maxlength attribute.
         */
        "maxlength"?: number;
        /**
          * The input's min attribute.
         */
        "min"?: number;
        /**
          * The input's minlength attribute.
         */
        "minlength"?: number;
        "name"?: string;
        "onBlurChange"?: (event: CustomEvent<any>) => void;
        "onFocusChange"?: (event: CustomEvent<any>) => void;
        "onValueChange"?: (event: CustomEvent<any>) => void;
        /**
          * The input's pattern attribute.
         */
        "pattern"?: string;
        /**
          * Set to true to draw a pill-style input with rounded edges.
         */
        "pill"?: boolean;
        /**
          * The input's placeholder text.
         */
        "placeholder"?: string;
        /**
          * Set to true for a readonly input.
         */
        "readonly"?: boolean;
        /**
          * The input's required attribute.
         */
        "required"?: boolean;
        "size"?: Size;
        /**
          * The input's step attribute.
         */
        "step"?: number;
        "togglePassword"?: boolean;
        "type"?: InputType;
        "valid"?: boolean;
        "value"?: string;
    }
    interface IntrinsicElements {
        "nxc-input": NxcInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nxc-input": LocalJSX.NxcInput & JSXBase.HTMLAttributes<HTMLNxcInputElement>;
        }
    }
}
